version: "3.9"
services:
  price_generator:
    image: price_generator
    environment:
      - REDIS_HOST=172.28.1.1
      - REDIS_PORT=6379
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      node_net:
        ipv4_address: 172.28.1.10
  price_buffer:
    image: price_buffer
    environment:
      - REDIS_HOST=172.28.1.1
      - REDIS_PORT=6379
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      node_net:
        ipv4_address: 172.28.1.9
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      node_net:
        ipv4_address: 172.28.1.1

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16